spring:
  application:
   name: Trip Planner Email
  mail:
    host: smtp.mail.ru
    port: 465
    username: nurs_sadyk@mail.ru
    password: CZbfkstmvNM3RprjMXPz
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

  cloud:
    stream:
      function:
        definition: consume;
      bindings:
        consume-in-0:
          destination: notify-members-event
      kafka:
        binder:
          brokers: localhost:9092

    circuitbreaker:
      resilience4j:
        instances:
          userClientCircuitBreaker:
            slidingWindowSize: 100
            permittedNumberOfCallsInHalfOpenState: 3
            waitDurationInOpenState: 10s
            failureRateThreshold: 50

server:
  port: 8181