spring:
  application:
   name: Trip Planner Email
  mail:
    host: smtp.mail.ru
    port: 465
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

  cloud:
    stream:
      function:
        definition: consume;
      bindings:
        consume-in-0:
          destination: notify-members-event
      kafka:
        binder:
          brokers: localhost:9092

    circuitbreaker:
      resilience4j:
        instances:
          userClientCircuitBreaker:
            slidingWindowSize: 100
            permittedNumberOfCallsInHalfOpenState: 3
            waitDurationInOpenState: 10s
            failureRateThreshold: 50
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

services:
  user-management: trip-planner-auth
server:
  port: 8181